FROM node:10

# Cd into app dir
WORKDIR /usr/src/app

ENV PORT 8080
ENV HOST 0.0.0.0

# Copy over node requirements
COPY package*.json ./

# Install node nodules
RUN npm install 

# Copy client code to container.
COPY . . 

# Build 
RUN npm run build 

# Start the container
CMD npm start